"""Pack visual/coll_compact.json into visual/coll_data.js for the standalone
collocation navigator widget (sanskrit_collocations.html, roadmap drain A27).

coll_compact.json is the already-published `regen_widgets.py` output ("top
collocations, same-sentence lemma co-occurrence"): 800 lemmas (n >= 317), each
with its POS and up to ~25 collocates split by part of speech — v (verbs),
nn (nouns), a (adjectives), o (other). Packing into a single
`window.COLL_DATA = {...}` script (rather than a fetch()ed JSON file) follows
the house pattern set by gen_concordance_data.py: a page opened by double-click
from disk cannot fetch() local JSON in most browsers (CORS), so companion data
ships as a script tag instead. The widget must be kept next to visual/ when
copied, same as the concordance / paradigm-trainer pairs.

This packer only re-wraps the published JSON — it never touches the SQLite
master. It validates the payload shape before writing so a schema drift in
coll_compact.json fails loudly here instead of rendering blank in the widget.

Run from the VisualDCS repo root:
    python gen_collocations_data.py
"""

import json
import os

REPO = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(REPO, "visual", "coll_compact.json")
OUT = os.path.join(REPO, "visual", "coll_data.js")

ALLOWED_POS = {"verb", "noun", "adj"}
COLL_KEYS = ("v", "nn", "a", "o")


def main():
    with open(SRC, encoding="utf-8") as fh:
        lemmas = json.load(fh)

    if len(lemmas) != 800:
        raise SystemExit(f"ERROR: expected 800 lemmas, got {len(lemmas)}")

    n_floor = None
    n_refs = 0
    for lemma, entry in lemmas.items():
        missing = {"n", "pos", *COLL_KEYS} - set(entry)
        if missing:
            raise SystemExit(f"ERROR: {lemma}: missing keys {sorted(missing)}")
        if entry["pos"] not in ALLOWED_POS:
            raise SystemExit(f"ERROR: {lemma}: unexpected pos {entry['pos']!r}")
        if not isinstance(entry["n"], int) or entry["n"] <= 0:
            raise SystemExit(f"ERROR: {lemma}: bad freq n={entry['n']!r}")
        if n_floor is None or entry["n"] < n_floor:
            n_floor = entry["n"]
        for key in COLL_KEYS:
            for pair in entry[key]:
                if (
                    not isinstance(pair, list)
                    or len(pair) != 2
                    or not isinstance(pair[0], str)
                    or not isinstance(pair[1], int)
                    or pair[1] <= 0
                ):
                    raise SystemExit(f"ERROR: {lemma}[{key}]: bad collocate {pair!r}")
                n_refs += 1

    out = {
        "generatedBy": "gen_collocations_data.py (A27) from visual/coll_compact.json",
        "lemmaCount": len(lemmas),
        "minFreq": n_floor,
        "collocateRefs": n_refs,
        "lemmas": lemmas,
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by gen_collocations_data.py (A27) -- do not hand-edit.\n")
        fh.write("window.COLL_DATA = ")
        json.dump(out, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"Wrote {OUT}: {len(lemmas):,} lemmas, {n_refs:,} collocate refs, "
          f"min freq {n_floor:,}, {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
