"""Pack visual/conc_part{1,2,3}.json + conc_totals.json into visual/conc_data.js
for the standalone concordance search widget (sanskrit_concordance.html, H1505).

The three part files already partition the 6,423 searchable forms (no key overlap);
conc_totals.json's counts are redundant with each form's own [0] field (verified
below) and exist only as a legacy quick-lookup file, unused by this widget. Packing
into a single `window.CONC_DATA = {...}` script (rather than three fetch()ed JSON
files) follows the house pattern set by gen_paradigm_nominal.py / gen_paradigm_
attested.py: file:// pages opened by double-click cannot fetch() local JSON in most
browsers (CORS), so large data ships as a script tag instead.

Run from the VisualDCS repo root:
    python gen_concordance_data.py
"""

import json
import os

REPO = os.path.dirname(os.path.abspath(__file__))
PARTS = [os.path.join(REPO, "visual", f"conc_part{n}.json") for n in (1, 2, 3)]
TOTALS = os.path.join(REPO, "visual", "conc_totals.json")
OUT = os.path.join(REPO, "visual", "conc_data.js")


def main():
    merged = {}
    for path in PARTS:
        with open(path, encoding="utf-8") as fh:
            part = json.load(fh)
        overlap = set(part) & set(merged)
        if overlap:
            raise SystemExit(f"ERROR: {path} re-keys {len(overlap)} forms already seen")
        merged.update(part)

    with open(TOTALS, encoding="utf-8") as fh:
        totals = json.load(fh)
    if set(totals) != set(merged):
        raise SystemExit("ERROR: conc_totals.json keys don't match the merged part files")
    mismatched = [f for f, n in totals.items() if merged[f][0] != n]
    if mismatched:
        raise SystemExit(f"ERROR: total-count mismatch for {mismatched[:5]}")

    out = {
        "generatedBy": "gen_concordance_data.py (H1505)",
        "formCount": len(merged),
        "forms": merged,
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by gen_concordance_data.py (H1505) -- do not hand-edit.\n")
        fh.write("window.CONC_DATA = ")
        json.dump(out, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"Wrote {OUT}: {len(merged):,} forms, {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
