<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <ProjectOptions>
    <Version Value="12"/>
    <PathDelim Value="\"/>
    <General>
      <Title Value="dic32"/>
      <ResourceType Value="res"/>
      <XPManifest>
        <DpiAware Value="Per-monitor"/>
        <LongPathAware Value="True"/>
        <TextName Value="Electronic Sanskrit Dictionary"/>
        <TextDesc Value="Saudamani v5.0"/>
      </XPManifest>
      <Icon Value="0"/>
    </General>
    <VersionInfo>
      <UseVersionInfo Value="True"/>
      <AutoIncrementBuild Value="True"/>
      <MajorVersionNr Value="5"/>
      <BuildNr Value="175"/>
      <Attributes pvaDebug="True" pvaPreRelease="True"/>
      <StringTable OriginalFilename="Dic64" ProductName="Saudamani Electronic Sanskrit Dictionary" ProductVersion="5.0 BETA"/>
    </VersionInfo>
    <MacroValues Count="1">
      <Macro1 Name="LCLWidgetType" Value="win32"/>
    </MacroValues>
    <BuildModes Active="Default">
      <Item Name="Default" Default="True"/>
      <SessionMatrixOptions Count="1">
        <Item1 ID="999538667762" Modes="Default" Type="IDEMacro" MacroName="LCLWidgetType" Value="win32"/>
      </SessionMatrixOptions>
    </BuildModes>
    <PublishOptions>
      <Version Value="2"/>
    </PublishOptions>
    <RunParams>
      <FormatVersion Value="2"/>
      <Modes>
        <Mode Name="default"/>
      </Modes>
    </RunParams>
    <RequiredPackages>
      <Item>
        <PackageName Value="TAChartLazarusPkg"/>
      </Item>
      <Item>
        <PackageName Value="pl_Cindy"/>
      </Item>
      <Item>
        <PackageName Value="SynEditDsgn"/>
      </Item>
      <Item>
        <PackageName Value="SynEdit"/>
      </Item>
      <Item>
        <PackageName Value="richmemopackage"/>
      </Item>
      <Item>
        <PackageName Value="richmemo_design"/>
      </Item>
      <Item>
        <PackageName Value="CEF4Delphi_Lazarus"/>
      </Item>
      <Item>
        <PackageName Value="LCL"/>
      </Item>
      <Item>
        <PackageName Value="TurboPowerIPro"/>
      </Item>
      <Item>
        <PackageName Value="FrameViewer09"/>
      </Item>
    </RequiredPackages>
    <Units>
      <Unit>
        <Filename Value="dic32.lpr"/>
        <IsPartOfProject Value="True"/>
        <EditorIndex Value="6"/>
        <TopLine Value="24"/>
        <CursorPos X="6" Y="31"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="unit1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Unit1"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="21" Y="5"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="gram.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="NN"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="11"/>
        <CursorPos Y="22"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="gdepo.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="gd"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="10"/>
        <CursorPos X="51" Y="4"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="gfr.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="gres"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="13"/>
        <CursorPos Y="20"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="ver1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="vr"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="142"/>
        <CursorPos X="27" Y="145"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="FREE\sfo.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="sf"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="26" Y="2"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="fmain.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="fgif"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="dcon.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="dc"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="20"/>
        <TopLine Value="501"/>
        <CursorPos Y="506"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="ssv.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="RDR"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="8"/>
        <TopLine Value="246"/>
        <CursorPos Y="255"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="sh1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="shis"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="122"/>
        <CursorPos X="43" Y="128"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="adepo.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Apte"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="ngh.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="ng"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="173"/>
        <CursorPos X="22" Y="177"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="ent1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Ent"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="132"/>
        <CursorPos X="2" Y="146"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="h1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Hl"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="23" Y="6"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="ht1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="ht"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="129"/>
        <CursorPos X="75" Y="141"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="tt1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="tt"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="38"/>
        <CursorPos X="65" Y="48"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="keyboard1.pas"/>
        <IsPartOfProject Value="True"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="grmx.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="wc"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="61"/>
        <CursorPos X="72" Y="69"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="unit2xxx.pas"/>
        <IsPartOfProject Value="True"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="12" Y="2"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="ds1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="DSet"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="49"/>
        <CursorPos X="26" Y="57"/>
        <UsageCount Value="201"/>
      </Unit>
      <Unit>
        <Filename Value="tcf.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="TTS"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="15"/>
        <TopLine Value="346"/>
        <CursorPos X="17" Y="354"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="lns1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Lns"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="24"/>
        <TopLine Value="79"/>
        <CursorPos X="39" Y="85"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="wrf.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="WR"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="23"/>
        <TopLine Value="725"/>
        <CursorPos Y="741"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="vf2.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="VForms"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="10"/>
        <TopLine Value="158"/>
        <CursorPos X="32" Y="62"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="tcompare.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="CT"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="7"/>
        <TopLine Value="268"/>
        <CursorPos X="41" Y="272"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="stans.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="STA"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="StAns"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="52"/>
        <CursorPos X="34" Y="61"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="tsn.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Sinta"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="TsN"/>
        <EditorIndex Value="14"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="rusk.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="rk"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="46"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="trunit.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="TRE"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="omf.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="of1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="45"/>
        <CursorPos X="64" Y="49"/>
        <UsageCount Value="201"/>
      </Unit>
      <Unit>
        <Filename Value="parals.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="prl"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <CursorPos Y="304"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="lgg.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="liga"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="26"/>
        <CursorPos Y="39"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="wtc.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="WT1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="wTC"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="79"/>
        <CursorPos X="64" Y="86"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="tinfo.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form2"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Tinfo"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="28"/>
        <CursorPos X="37" Y="42"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="df.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form3"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="dF"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="94"/>
        <CursorPos Y="99"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="syn.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form4"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="30"/>
        <CursorPos Y="23"/>
        <UsageCount Value="201"/>
      </Unit>
      <Unit>
        <Filename Value="fdic.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form5"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="45"/>
        <CursorPos X="26" Y="45"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="vpref.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form6"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="21"/>
        <CursorPos X="66" Y="36"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="tema.pas"/>
        <IsPartOfProject Value="True"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="201"/>
      </Unit>
      <Unit>
        <Filename Value="lex2.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form7"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="12"/>
        <TopLine Value="43"/>
        <CursorPos X="42" Y="51"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="lpak.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="lp"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <TopLine Value="1612"/>
        <CursorPos X="58" Y="1620"/>
        <UsageCount Value="203"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="params.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form8"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="17"/>
        <TopLine Value="239"/>
        <CursorPos X="39" Y="260"/>
        <UsageCount Value="201"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="sintagma1.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="sintagma"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="454"/>
        <CursorPos X="31" Y="455"/>
        <UsageCount Value="200"/>
      </Unit>
      <Unit>
        <Filename Value="acat.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form9"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="16"/>
        <TopLine Value="57"/>
        <CursorPos X="11" Y="66"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="thank.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form10"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Thank"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="75"/>
        <CursorPos X="48" Y="75"/>
        <UsageCount Value="201"/>
      </Unit>
      <Unit>
        <Filename Value="th2.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Form11"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="13"/>
        <TopLine Value="34"/>
        <CursorPos Y="42"/>
        <UsageCount Value="200"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="krr.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="kr"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="9"/>
        <TopLine Value="135"/>
        <CursorPos X="19" Y="139"/>
        <UsageCount Value="195"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="trwin.pas"/>
        <IsPartOfProject Value="True"/>
        <ComponentName Value="Tr"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="19"/>
        <TopLine Value="122"/>
        <CursorPos Y="135"/>
        <UsageCount Value="154"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="edepo.pas"/>
        <ComponentName Value="ED"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="EDepo"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="13"/>
        <UsageCount Value="188"/>
      </Unit>
      <Unit>
        <Filename Value="eda1.pas"/>
        <ComponentName Value="EDA"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Eda1"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="120"/>
        <CursorPos X="13" Y="121"/>
        <UsageCount Value="187"/>
      </Unit>
      <Unit>
        <Filename Value="poisk.pas"/>
        <ComponentName Value="Form1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <IsVisibleTab Value="True"/>
        <EditorIndex Value="5"/>
        <TopLine Value="1131"/>
        <CursorPos Y="1133"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="depo1.pas"/>
        <ComponentName Value="depo"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="53"/>
        <CursorPos X="43" Y="57"/>
        <UsageCount Value="100"/>
      </Unit>
      <Unit>
        <Filename Value="keybrd.lfm"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="22"/>
        <UsageCount Value="6"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="keybrd.pas"/>
        <ComponentName Value="symba"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="227"/>
        <CursorPos X="5" Y="235"/>
        <UsageCount Value="100"/>
      </Unit>
      <Unit>
        <Filename Value="repo1.pas"/>
        <ComponentName Value="Tz"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Repo1"/>
        <EditorIndex Value="2"/>
        <TopLine Value="466"/>
        <CursorPos X="45" Y="471"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="reult1.pas"/>
        <ComponentName Value="resform"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="21"/>
        <TopLine Value="444"/>
        <CursorPos X="5" Y="452"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="tema1.pas"/>
        <ComponentName Value="tema"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="4"/>
        <TopLine Value="397"/>
        <CursorPos X="45" Y="404"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="edepo.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="8"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="depo1.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="10"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="depo2.pas"/>
        <ComponentName Value="DP"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="24"/>
        <CursorPos X="49" Y="29"/>
        <UsageCount Value="69"/>
      </Unit>
      <Unit>
        <Filename Value="help1.pas"/>
        <ComponentName Value="hlp"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="11"/>
        <CursorPos Y="6"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="C:\Users\Владимир\AppData\Local\lazarus\onlinepackagemanager\packages\richmemo\richmemofactory.pas"/>
        <UnitName Value="RichMemoFactory"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="33"/>
        <CursorPos Y="35"/>
        <UsageCount Value="3"/>
      </Unit>
      <Unit>
        <Filename Value="sfo.pas"/>
        <ComponentName Value="sf"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="22"/>
        <TopLine Value="290"/>
        <CursorPos Y="306"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="ent1.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="78"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="tx1.pas"/>
        <ComponentName Value="DCS1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="18"/>
        <TopLine Value="283"/>
        <CursorPos X="62" Y="284"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\grids.pas"/>
        <UnitName Value="Grids"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="9890"/>
        <CursorPos Y="9899"/>
        <UsageCount Value="39"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\include\menu.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="214"/>
        <CursorPos Y="221"/>
        <UsageCount Value="1"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\interfaces\win32\win32listsl.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="144"/>
        <CursorPos Y="153"/>
        <UsageCount Value="31"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\include\control.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="5790"/>
        <CursorPos Y="5798"/>
        <UsageCount Value="15"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\forms.pp"/>
        <UnitName Value="Forms"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="856"/>
        <CursorPos X="14" Y="863"/>
        <UsageCount Value="5"/>
      </Unit>
      <Unit>
        <Filename Value="unt.pas"/>
        <ComponentName Value="un"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Unt"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="266"/>
        <CursorPos X="27" Y="266"/>
        <UsageCount Value="94"/>
      </Unit>
      <Unit>
        <Filename Value="C:\lazarus\lcl\include\application.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="2038"/>
        <CursorPos Y="2047"/>
        <UsageCount Value="4"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\grids.pas"/>
        <UnitName Value="Grids"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="5493"/>
        <CursorPos Y="5501"/>
        <UsageCount Value="15"/>
      </Unit>
      <Unit>
        <Filename Value="E:\!\out7\done\RAMA\unt.pas"/>
        <ComponentName Value="Form1"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="Unit1"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="2"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\lclmessageglue.pas"/>
        <UnitName Value="LCLMessageGlue"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="109"/>
        <CursorPos X="18" Y="115"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\include\application.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="1400"/>
        <CursorPos Y="1410"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\interfaces\win32\win32callback.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="2025"/>
        <CursorPos Y="2034"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\lclclasses.pp"/>
        <UnitName Value="LCLClasses"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="171"/>
        <CursorPos Y="183"/>
        <UsageCount Value="5"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\interfaces\win32\win32object.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="364"/>
        <CursorPos Y="377"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="vd1.pas"/>
        <ComponentName Value="verdir"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="3"/>
        <TopLine Value="993"/>
        <CursorPos X="6" Y="998"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\include\customform.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="2385"/>
        <CursorPos Y="2393"/>
        <UsageCount Value="16"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\forms.pp"/>
        <UnitName Value="Forms"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="2"/>
      </Unit>
      <Unit>
        <Filename Value="kn.pas"/>
        <ComponentName Value="kkn"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="25"/>
        <TopLine Value="504"/>
        <CursorPos X="56" Y="517"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
        <LoadedDesigner Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="dmk1.pas"/>
        <ComponentName Value="dmk"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="40"/>
        <CursorPos X="17" Y="11"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="frs.pas"/>
        <ComponentName Value="FR"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="1"/>
        <TopLine Value="405"/>
        <CursorPos X="101" Y="416"/>
        <UsageCount Value="100"/>
        <Loaded Value="True"/>
      </Unit>
      <Unit>
        <Filename Value="rts.pas"/>
        <ComponentName Value="Roots"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <UnitName Value="RTS"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="13"/>
        <CursorPos X="46" Y="21"/>
        <UsageCount Value="95"/>
      </Unit>
      <Unit>
        <Filename Value="ched1.pas"/>
        <ComponentName Value="chd"/>
        <HasResources Value="True"/>
        <ResourceBaseClass Value="Form"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="10"/>
        <CursorPos X="29" Y="22"/>
        <UsageCount Value="5"/>
      </Unit>
      <Unit>
        <Filename Value="backup\repo1.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="4"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\include\control.inc"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="3596"/>
        <CursorPos Y="3605"/>
        <UsageCount Value="21"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\lcl\controls.pp"/>
        <UnitName Value="Controls"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="1566"/>
        <CursorPos X="28" Y="1575"/>
        <UsageCount Value="7"/>
      </Unit>
      <Unit>
        <Filename Value="rts.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="10"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="frs.lfm"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="21"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="F:\5\PHISICS.PAS"/>
        <UnitName Value="Illustratsiya_poleta_mototsiklista_s_tramplina"/>
        <EditorIndex Value="-1"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\components\lazutils\laztracer.pas"/>
        <UnitName Value="LazTracer"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="49"/>
        <CursorPos X="18" Y="54"/>
        <UsageCount Value="10"/>
      </Unit>
      <Unit>
        <Filename Value="ssv.lfm"/>
        <EditorIndex Value="-1"/>
        <CursorPos X="19"/>
        <UsageCount Value="17"/>
        <DefaultSyntaxHighlighter Value="LFM"/>
      </Unit>
      <Unit>
        <Filename Value="G:\lazarus\components\tachart\tagraph.pas"/>
        <UnitName Value="TAGraph"/>
        <EditorIndex Value="-1"/>
        <TopLine Value="1596"/>
        <CursorPos Y="1603"/>
        <UsageCount Value="10"/>
      </Unit>
    </Units>
    <JumpHistory HistoryIndex="29">
      <Position>
        <Filename Value="trwin.pas"/>
        <Caret Line="77" TopLine="71"/>
      </Position>
      <Position>
        <Filename Value="trwin.pas"/>
        <Caret Line="102" TopLine="97"/>
      </Position>
      <Position>
        <Filename Value="trwin.pas"/>
        <Caret Line="133" TopLine="122"/>
      </Position>
      <Position>
        <Filename Value="trwin.pas"/>
        <Caret Line="135" TopLine="122"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1263" Column="28" TopLine="1253"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1262" Column="23" TopLine="1254"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1263" Column="23" TopLine="1255"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1255" TopLine="1253"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1256" TopLine="1253"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1316" Column="15" TopLine="1302"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1317" Column="15" TopLine="1303"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1318" Column="15" TopLine="1304"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="1222" Column="6" TopLine="978"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="566" Column="14" TopLine="560"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="567" Column="14" TopLine="561"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="575" TopLine="572"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="576" TopLine="573"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="577" TopLine="574"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="578" TopLine="575"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="585" TopLine="582"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="509" Column="26" TopLine="506"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="508" Column="27" TopLine="501"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="511" Column="29" TopLine="502"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="510" Column="29" TopLine="501"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="508" TopLine="502"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="509" TopLine="503"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="508" TopLine="502"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="509" TopLine="503"/>
      </Position>
      <Position>
        <Filename Value="kn.pas"/>
        <Caret Line="515" Column="3" TopLine="503"/>
      </Position>
      <Position>
        <Filename Value="dic32.lpr"/>
        <Caret Line="15" Column="19" TopLine="7"/>
      </Position>
    </JumpHistory>
  </ProjectOptions>
  <CompilerOptions>
    <Version Value="11"/>
    <PathDelim Value="\"/>
    <Target>
      <Filename Value="dic32"/>
    </Target>
    <SearchPaths>
      <IncludeFiles Value="$(ProjOutDir)"/>
      <OtherUnitFiles Value="C:\Users\Владимир\AppData\Local\lazarus\onlinepackagemanager\packages\richmemo\"/>
      <UnitOutputDirectory Value="lib\$(TargetCPU)-$(TargetOS)"/>
    </SearchPaths>
    <CodeGeneration>
      <TargetOS Value="win64"/>
    </CodeGeneration>
    <Linking>
      <Debugging>
        <DebugInfoType Value="dsDwarf3"/>
      </Debugging>
      <Options>
        <Win32>
          <GraphicApplication Value="True"/>
        </Win32>
      </Options>
    </Linking>
    <Other>
      <Verbosity>
        <ShoLineNum Value="True"/>
        <ShowExecInfo Value="True"/>
      </Verbosity>
    </Other>
  </CompilerOptions>
  <Debugging>
    <BreakPoints>
      <Item>
        <Kind Value="bpkSource"/>
        <WatchScope Value="wpsLocal"/>
        <WatchKind Value="wpkWrite"/>
        <Source Value="eda1.pas"/>
        <Line Value="293"/>
      </Item>
      <Item>
        <Kind Value="bpkSource"/>
        <WatchScope Value="wpsLocal"/>
        <WatchKind Value="wpkWrite"/>
        <Source Value="eda1.pas"/>
        <Line Value="78"/>
      </Item>
    </BreakPoints>
    <Exceptions>
      <Item>
        <Name Value="EAbort"/>
      </Item>
      <Item>
        <Name Value="ECodetoolError"/>
      </Item>
      <Item>
        <Name Value="EFOpenError"/>
      </Item>
      <Item>
        <Name Value="Exception"/>
      </Item>
      <Item>
        <Name Value="ELayoutException"/>
      </Item>
    </Exceptions>
  </Debugging>
</CONFIG>
