#!/usr/bin/env python3
"""Bake the nominal class-split side-car into a build-time JS global (H5741).

visual/paradigm_nominal_class_split_adj.json (H4011) had ZERO consumers — the
panel this script feeds closes that. The dashboard stack is file-based: data
reaches a page as `window.*` globals from sibling *_data.js files (never a
client-side fetch), so this builder converts the JSON side-car into
visual/paradigm_nominal_class_split_adj_data.js.

READ-ONLY on the side-car: the JSON is regenerated only by its own producer
(src/DCS-data-2026/split_pooled_nominal_classes_adj.py, H4011). This script
never re-derives or rewrites it; it fails loudly if the artifact is missing.

Faithful-but-trimmed payload: verdict-group counts are kept EXACT; exemplar
lists keep the side-car's own 12-item cap; perLemmaAntAdj ships COMPLETE (it
is the table fallback + CSV export source). Data date = the side-car's last
content commit (git log -1 --format=%as), stamped at build time.

Usage:
    python tools/build_nominal_classsplit_panel.py            # build
    python tools/build_nominal_classsplit_panel.py --check    # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = ROOT / "visual" / "paradigm_nominal_class_split_adj.json"
OUT = ROOT / "visual" / "paradigm_nominal_class_split_adj_data.js"

VERDICT_ORDER = ("one_lexeme_two_spellings", "at_only", "ant_only",
                 "two_headwords", "unresolved")
VERDICT_RU = {
    "one_lexeme_two_spellings": "одна лемма, два написания (-ат/-ант)",
    "at_only": "только -ат (одно написание)",
    "ant_only": "только -ант (одно написание)",
    "two_headwords": "два разных заголовочных слова",
    "unresolved": "не разрешено эвристикой",
}


def data_date() -> str:
    r = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-1", "--format=%as", "--", str(SRC)],
        capture_output=True, text=True, timeout=60)
    return r.stdout.strip() if r.returncode == 0 else "unknown"


def build_payload(d: dict) -> dict:
    per_lemma = d.get("perLemmaAntAdj") or []
    verdicts = {}
    for k in VERDICT_ORDER:
        g = (d.get("antAdjByVerdict") or {}).get(k) or {}
        verdicts[k] = {
            "label": VERDICT_RU.get(k, k),
            "lemmaIds": g.get("lemmaIds", 0),
            "tokens": g.get("tokens", 0),
            "exemplars": g.get("exemplars", []),
        }
    return {
        "meta": {
            "generatedBy": d.get("generatedBy", ""),
            "predecessor": d.get("predecessor", ""),
            "schemaVersion": d.get("schemaVersion", ""),
            "dataDate": data_date(),
            "sourceArtifact": "visual/paradigm_nominal_class_split_adj.json",
            "panelBuilder": "tools/build_nominal_classsplit_panel.py (H5741)",
            "reconciles": bool(d.get("reconciles")),
            "pinnedPairOk": bool(d.get("pinnedPairOk")),
            "nLemmas": len(per_lemma),
            "nTokensAntPool": (d.get("antPool") or {}).get("tokens"),
        },
        "antPool": d.get("antPool") or {},
        "verdicts": verdicts,
        "reconciliation": d.get("reconciliation") or [],
        "pinnedPair": d.get("pinnedPair") or {},
        "iiNonNoun": d.get("iiNonNoun") or {},
        "unresolvedResidual": d.get("unresolvedResidual") or {},
        "perLemma": per_lemma,
    }


def render_js(payload: dict) -> str:
    body = json.dumps(payload, ensure_ascii=False,
                      separators=(",", ":")).encode("utf-8")
    return ("// AUTO-GENERATED by tools/build_nominal_classsplit_panel.py "
            "(H5741) — do not hand-edit.\n"
            "// Source of truth: visual/paradigm_nominal_class_split_adj.json "
            "(read-only side-car, H4011).\n"
            "window.NOMINAL_CLASS_SPLIT_ADJ = "
            + body.decode("utf-8") + ";\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 when the committed data.js is stale vs the JSON")
    a = ap.parse_args()
    if not SRC.is_file():
        print(f"FAIL: side-car artifact missing: {SRC}", file=sys.stderr)
        return 1
    d = json.loads(SRC.read_text(encoding="utf-8"))
    js = render_js(build_payload(d))
    if a.check:
        want = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if want != js:
            print(f"DRIFT: {OUT.relative_to(ROOT)} is stale vs the side-car — "
                  f"re-run tools/build_nominal_classsplit_panel.py", file=sys.stderr)
            return 1
        print(f"check OK: {OUT.relative_to(ROOT)} matches the side-car")
        return 0
    OUT.write_text(js, encoding="utf-8")
    m = payload_meta = json.loads(js.split("= ", 1)[1].rsplit(";\n", 1)[0])["meta"]
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size // 1024} KB)  "
          f"nLemmas={m['nLemmas']}  dataDate={m['dataDate']}  "
          f"reconciles={m['reconciles']}")
    return 0


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    raise SystemExit(main())
